apiVersion: v1
kind: Service
metadata:
  name: rag-agent
  labels:
    app.kubernetes.io/name: rag-agent
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: challenge-k8s-pro
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rag-agent
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
