apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/pdb.yaml

images:
  - name: rag-agent
    newName: rag-agent
    newTag: v2.0
